### ISSUE TITLE
Game/Engine Parent & Child Vars do not reset in servers after the match ends

### ISSUE THREAD

**Issue by abcd-alrayan** [plutoniummod/bug-tracker#26]
### What happened?

I'm assuming this is an error/unintended behavior

in Servers, the parent & child vars do not reset after the match ends, I can see that by running this function to track it in console_zm

//
`
Print_Console()
{
	for(;;)
	{
		level waittill( "start_of_round" );

		printLn("oooooooooooooooooooooooooooooooooooooooo" );//for easy search

		printLn("Start of Round: " + level.round_number );

		printLn("Number of players: " + level.players.size );

		foreach( player in level.players )
		{
			printLn(player.name );
		}
		cmdexec("scriptusage");
	}
}
`
//
the vars carry on through multiple games until the server crash due to script vars error.

there is a vote system

[map_vote.txt](https://github.com/user-attachments/files/19621971/map_vote.txt)

### Expected result

The vars should reset to 0 and then gets assigned again like a normal custom games match when the game ends.

### Steps to reproduce

1. Have a server running
2. Just track the console log in a server and see
3. (optional) have many players join and leave

### Affected game(s)

BO2 Zombies (T6ZM)

### Affected component(s)

Server (dedi)

### Plutonium version

r4542

### Relevant logs

an example of the vars persisting through games

parent variables used: 7029 / 32768
child variables used: 32487 / 65536
max parent variables used 17638 / 32768
max child variables used 64828 / 65536
checksum0: 0x265BC0BF
checksum1: 0x1F4D5A23
checksum2: 0x0000233F

oooooooooooooooooooooooooooooooooooooooo
Start of Round: 3
Number of players: 4

### Operating system

windows server 2019

### Plutonium profile

https://forum.plutonium.pw/user/ivobardolf

### Discord username

Ivobardolf

**Comment by ineedbots** [comment]
Update to the latest version, this has been addressed.

**Comment by abcd-alrayan** [comment]
after updating to r4814, the issue still seems to persist, anything that I can provide?

**Comment by ineedbots** [comment]
if you could provide the full console log file that would help of when the error occurred

**Comment by ineedbots** [comment]
or rather; this might just be a misinterpretation of the issue here, I think everything is working as intended, theres a lot of gsc activity before when your script calls the scriptusage function, therefore there will be a significant amount of variable usage.

there 'was' and issue where if you were to error, not all of the variables would be free'd and permanently allocated, but this has been fixed.

**Comment by abcd-alrayan** [comment]
the server doesn't "Error", the match ends normally and a new one starts, the problem is that the vars don't reset after every match end.

I think it's still there because the start of the server the match starts with max child vars at 28k~30k, but then later on the match starts with 59k vars that the previous match ended on, it shouldn't start at that number when earlier it started at almost half of it.

**Comment by ineedbots** [comment]
I am still pretty sure everything is operating as normal, if there were leaks in between matches, you should be able to do `killserver` and then `scriptusage`, you should see 0 usage for everything. If the game is `fastrestart`ing, then some variables carry over as intended.

**Comment by abcd-alrayan** [comment]
> I am still pretty sure everything is operating as normal, if there were leaks in between matches, you should be able to do `killserver` and then `scriptusage`, you should see 0 usage for everything.

so leaking vars between matches is normal server behavior? because in solo/custom games it doesn't, Should the vars in the server reset after a "Game Over" happen and then the screen fades to black and goes to the pre-game menu like how it is in solo and custom games without any commands? just ends and a then a new one start.

if the answer is "No it shouldn't reset" then this is normal server behavior, currently The vars are persisting through matches, then servers have to restart after every match to clean it.

if the answer is "Yes it should reset" , Then this is the problem I'm having, the vars are not resetting upon a match ending via everyone dying and "Game Over" happens then it fades to black etc,

If you want you can look at the log and search `ooooooooooooo` and `map_rotate` so you see the usage after every round and after every match ends.

**Comment by ineedbots** [comment]
this issue would be widespread on dedicated server, of whom never complained about the vanilla scripts running out script variables, I can only accept that this is normal behaviour

**Comment by ineedbots** [comment]
I just tested this, I simply started a match, and did `scriptusage`.
![Image](https://github.com/user-attachments/assets/45e3b2d5-894e-4253-863a-8387e9d61c60)

Then I `map_restart`, and did `scriptusage` again after the map had reloaded.
![Image](https://github.com/user-attachments/assets/4a1ff5c5-8beb-4585-8a74-cd04822793ef)

And one more `map_restart` and `scriptusage`.
![Image](https://github.com/user-attachments/assets/6623c010-e7e5-4c82-8ec4-145c85b2c8a5)

There is no upwards trend for the variables here

**Comment by ineedbots** [comment]
I am NOT using the mapvote mod however, it possible that mod has a gsc leak somewhere.

**Comment by abcd-alrayan** [comment]
> There is no upwards trend for the variables here

maybe I didn't explain it well, it's not an upward trend for variables, the variables do not reset properly after the games end, for example if you reach round 30 with 3 players, the variables after the game ends do not fully reset back to 28k~ ish, it stays at 35K~40K.

I asked someone else to run the test on tranzit only, no map vote and he got the same issue I had, he had an active server with people joining & playing & leaving etc,

You can also play for many rounds solo but that doesn't sound like a good thing to do since it would take many hours, if someone can use the function I provided to see if they also have the same issue, granted it needs to be an active server.

sorry if I'm not explaining well, and thank you for taking the time to test.

**Comment by ineedbots** [comment]
closing this as it seems to be a non-issue and just vanilla behaviour
